nohup: ignoring input
[2025-06-09 17:12:57] [INFO    ] discord.client: logging in using static token
[2025-06-09 17:12:58] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ba9e47cf74e0877600e547a66eb32d20).
[2025-06-09 17:52:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-09 17:56:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-09 18:59:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-09 20:31:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-09 21:38:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-09 23:27:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 02:12:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 04:05:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 05:48:55] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 05:55:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 09:30:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 09:49:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 11:04:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 11:57:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 14:05:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 16:44:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 20:10:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 21:35:37] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 22:36:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 23:50:39] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-10 23:55:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 01:03:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 01:42:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 03:48:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 04:02:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 04:43:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 05:32:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 07:35:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 09:20:08] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/media/myfiles/rintemo/discord_bot.py", line 72, in <module>
    client.run(DISCORD_TOKEN)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/client.py", line 906, in run
    asyncio.run(runner())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1987, in _run_once
    handle._run()
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/client.py", line 481, in _run_event
    await coro(*args, **kwargs)
  File "/media/myfiles/rintemo/discord_bot.py", line 57, in on_message
    response = requests.post(FLASK_BACKEND_URL, data={
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)

[2025-06-11 09:20:18] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "/media/myfiles/rintemo/discord_bot.py", line 72, in <module>
    client.run(DISCORD_TOKEN)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/client.py", line 906, in run
    asyncio.run(runner())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1987, in _run_once
    handle._run()
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/client.py", line 481, in _run_event
    await coro(*args, **kwargs)
  File "/media/myfiles/rintemo/discord_bot.py", line 57, in on_message
    response = requests.post(FLASK_BACKEND_URL, data={
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)

[2025-06-11 09:20:25] [ERROR   ] discord.client: Attempting a reconnect in 1.53s
Traceback (most recent call last):
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/client.py", line 704, in connect
    await self.ws.poll_event()
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/gateway.py", line 627, in poll_event
    await self.received_message(msg.data)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/gateway.py", line 532, in received_message
    await self.send_as_json(beat)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/gateway.py", line 663, in send_as_json
    await self.send(utils._to_json(data))
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/gateway.py", line 659, in send
    await self.socket.send_str(data)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/aiohttp/client_ws.py", line 245, in send_str
    await self._writer.send_frame(
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/aiohttp/_websocket/writer.py", line 126, in send_frame
    raise ClientConnectionResetError("Cannot write to closing transport")
aiohttp.client_exceptions.ClientConnectionResetError: Cannot write to closing transport
[2025-06-11 09:20:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 10:55:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 11:59:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 14:09:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 15:35:55] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 15:47:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 16:38:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 17:00:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ba9e47cf74e0877600e547a66eb32d20.
[2025-06-11 18:13:16] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2025-06-11 18:13:22] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 568fc408b882efffb1fc315f8c0241d9).
[2025-06-11 18:56:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-11 20:30:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-11 21:56:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-11 22:11:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-11 22:25:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 00:16:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 01:39:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 04:07:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 07:41:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 09:36:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 10:08:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 10:50:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 12:37:20] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 12:53:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 14:36:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 16:46:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 17:44:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 568fc408b882efffb1fc315f8c0241d9.
[2025-06-12 18:18:18] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
🤖 Logged in as Rin#2704
🤖 Logged in as Rin#2704
Traceback (most recent call last):
  File "/media/myfiles/rintemo/discord_bot.py", line 72, in <module>
    client.run(DISCORD_TOKEN)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/client.py", line 906, in run
    asyncio.run(runner())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/client.py", line 895, in runner
    await self.start(token, reconnect=reconnect)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/client.py", line 824, in start
    await self.connect(reconnect=reconnect)
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/client.py", line 704, in connect
    await self.ws.poll_event()
  File "/media/myfiles/rintemo/myenv/lib/python3.12/site-packages/discord/gateway.py", line 650, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4004
